Repository snek-at/front-legacy, pull requests merged in 2019-11, with the labels that each got.

#6 Add basic setup 1
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  package.json
  public/index.html
  src/App.js
  src/Routes.js
  src/assets/React-icon.svg
  src/assets/agency-small.png
  src/assets/content/hire-us.jpg
  src/assets/content/outrun.jpg
  src/assets/content/projects.jpg
  src/assets/logo.svg
  src/assets/mdb-react-small.png
  src/components/atoms/DocsLink/index.jsx
  src/components/atoms/MenuLink/index.jsx
  src/components/atoms/index.js
  src/components/molecules/Footer/index.jsx
  src/components/molecules/Navbar/index.jsx
  src/components/molecules/index.js
  src/components/pages/HomePage/HomePage.scss
  src/components/pages/HomePage/index.jsx
  src/components/pages/index.js
  src/index.js
  src/index.scss
  src/registerServiceWorker.js
  src/utilities/_base.scss
  src/utilities/_variables.scss
Labels: enhancement

#7 Add readme 1
  README.md
Labels: enhancement

#12 Add intel 1
  .vscode/settings.json
  package.json
  src/App.js
  src/App.test.js
  src/intel/Database/Statements/Create/index.js
  src/intel/Database/Statements/Insert/index.js
  src/intel/Database/index.js
  src/intel/IntelData/index.js
  src/intel/IntelDummy/index.js
  src/intel/index.js
  src/intel/utils/UtilsGithub/index.js
  src/intel/utils/UtilsGitlab/index.js
Labels: feature

#14 Add ui 1
  src/Routes.js
  src/components/helpers/changeHue.js
  src/components/molecules/Avatar/index.jsx
  src/components/molecules/Calendar2D/calendar.scss
  src/components/molecules/Calendar2D/index.jsx
  src/components/molecules/Socialdata/index.jsx
  src/components/molecules/Socialdata/socialdata.scss
  src/components/molecules/TabContainer/index.jsx
  src/components/molecules/TabContainer/tabcontainer.scss
  src/components/molecules/TabSettingsContainer/index.jsx
  src/components/molecules/TabSettingsContainer/tabsettingscontainer.scss
  src/components/molecules/index.js
  src/components/organisms/tabs/Education/index.jsx
  src/components/organisms/tabs/Overview/index.jsx
  src/components/organisms/tabs/Projects/index.jsx
  src/components/organisms/tabs/Resume/index.jsx
  src/components/organisms/tabs/index.js
  src/components/pages/Profile/index.jsx
  src/components/pages/Profile/profile.scss
  src/components/pages/Settings/index.jsx
  src/components/pages/index.js
Labels: enhancement

#17 Add githubutils 1
  package.json
  src/App.test.js
  src/intel/IntelData/index.js
  src/intel/index.js
  src/intel/utils/UtilsApollo/index.js
  src/intel/utils/UtilsGithub/GqlData/index.js
  src/intel/utils/UtilsGithub/Translator/index.js
  src/intel/utils/UtilsGithub/index.js
Labels: feature

#22 Add ui 2
  package.json
  src/App.js
  src/components/molecules/Calendar2D/calendar.scss
  src/components/molecules/Calendar3D/calendar3d.scss
  src/components/molecules/Calendar3D/dummydata.js
  src/components/molecules/Calendar3D/index.jsx
  src/components/molecules/Calendar3D/obelisk.min.js
  src/components/molecules/LanguageChart/index.jsx
  src/components/molecules/Socialdata/index.jsx
  src/components/molecules/TabContainer/index.jsx
  src/components/molecules/index.js
  src/components/organisms/tabs/Overview/index.jsx
  src/components/pages/Profile/index.jsx
  src/components/pages/Profile/profile.scss
Labels: feature

#34 Add oauth 1
  src/Routes.js
  src/components/pages/OAuthRedirect/index.jsx
  src/components/pages/index.js
  src/intel/OAuthGithub/providers/github.ts
  src/intel/OAuthGithub/services/utilities.js
  src/react-app-env.d.ts
  tsconfig.json
Labels: feature

#25 Add githubutils 2
  src/intel/utils/UtilsGithub/Translator/index.js
Labels: bug

#29 Add coc 1
  CODE_OF_CONDUCT.md
Labels: enhancement

#28 Add contributing 1
  CONTRIBUTING.md
Labels: enhancement

#36 Add ui 3
  .env.template
  package.json
  src/App.js
  src/Routes.js
  src/components/molecules/Navbar/index.jsx
  src/components/molecules/index.js
  src/components/organisms/sections/Register/index.jsx
  src/components/organisms/sections/Register/register.scss
  src/components/organisms/sections/index.js
  src/components/organisms/tabs/Overview/index.jsx
  src/components/pages/Landing/index.jsx
  src/components/pages/Landing/landing.scss
  src/components/pages/Profile/index.jsx
  src/components/pages/index.js
  src/utilities/_base.scss
Labels: feature

#40 Add ui 4
  src/components/molecules/Navbar/index.jsx
  src/components/organisms/sections/Register/index.jsx
  src/components/pages/Landing/landing.scss
  src/utilities/_base.scss
Labels: enhancement

#45 Add contributing 1 to implement 2
  CONTRIBUTING.md
Labels: enhancement

#46 Add coc 1 to implement 2
  CODE_OF_CONDUCT.md
Labels: enhancement

#43 Add ui 1 to implement 2
  src/Routes.js
  src/components/helpers/changeHue.js
  src/components/molecules/Avatar/index.jsx
  src/components/molecules/Calendar2D/calendar.scss
  src/components/molecules/Calendar2D/index.jsx
  src/components/molecules/Socialdata/index.jsx
  src/components/molecules/Socialdata/socialdata.scss
  src/components/molecules/TabContainer/index.jsx
  src/components/molecules/TabContainer/tabcontainer.scss
  src/components/molecules/TabSettingsContainer/index.jsx
  src/components/molecules/TabSettingsContainer/tabsettingscontainer.scss
  src/components/molecules/index.js
  src/components/organisms/tabs/Education/index.jsx
  src/components/organisms/tabs/Overview/index.jsx
  src/components/organisms/tabs/Projects/index.jsx
  src/components/organisms/tabs/Resume/index.jsx
  src/components/organisms/tabs/index.js
  src/components/pages/Profile/index.jsx
  src/components/pages/Profile/profile.scss
  src/components/pages/Settings/index.jsx
  src/components/pages/index.js
Labels: enhancement

#44 Add githubutils 1 to implement 2
  package.json
  src/App.test.js
  src/intel/IntelData/index.js
  src/intel/index.js
  src/intel/utils/UtilsApollo/index.js
  src/intel/utils/UtilsGithub/GqlData/index.js
  src/intel/utils/UtilsGithub/Translator/index.js
  src/intel/utils/UtilsGithub/index.js
Labels: feature

#50 Add githubutils 2 to implement 2
  src/intel/utils/UtilsGithub/Translator/index.js
Labels: bug

#48 Add ui 2 to implement 2
  package.json
  src/App.js
  src/components/molecules/Calendar2D/calendar.scss
  src/components/molecules/Calendar3D/calendar3d.scss
  src/components/molecules/Calendar3D/dummydata.js
  src/components/molecules/Calendar3D/index.jsx
  src/components/molecules/Calendar3D/obelisk.min.js
  src/components/molecules/LanguageChart/index.jsx
  src/components/molecules/Socialdata/index.jsx
  src/components/molecules/TabContainer/index.jsx
  src/components/molecules/index.js
  src/components/organisms/tabs/Overview/index.jsx
  src/components/pages/Profile/index.jsx
  src/components/pages/Profile/profile.scss
Labels: enhancement

#52 Add oauth 1 to implement 2
  src/Routes.js
  src/components/pages/OAuthRedirect/index.jsx
  src/components/pages/index.js
  src/intel/OAuthGithub/providers/github.ts
  src/intel/OAuthGithub/services/utilities.js
  src/react-app-env.d.ts
  tsconfig.json
Labels: feature

#56 Improve intel 1 to implement 2
  src/intel/Database/Converter/index.js
  src/intel/Database/Statements/Create/index.js
  src/intel/Database/Statements/Insert/index.js
  src/intel/Database/Statements/Select/index.js
  src/intel/Database/index.js
  src/intel/IntelData/index.js
  src/intel/IntelDummy/index.js
  src/intel/index.js
Labels: enhancement, feature

#59 Add githubutils 3 to implement 2
  src/intel/utils/UtilsGithub/GqlData/index.js
  src/intel/utils/UtilsGithub/Translator/index.js
  src/intel/utils/UtilsGithub/index.js
Labels: enhancement

#60 Add ui 4 to implement 2
  src/components/molecules/Navbar/index.jsx
  src/components/organisms/sections/Register/index.jsx
  src/components/pages/Landing/landing.scss
  src/utilities/_base.scss
Labels: enhancement

#68 Add gitlabutils 2 to implement 2
  src/intel/utils/UtilsGitlab/index.js
Labels: bug

#62 Add oauth 2 to implement 2
  src/intel/OAuthGithub/providers/github.ts
Labels: enhancement

#65 Improve intel 2 to implement 2
  src/intel/Database/Converter/index.js
Labels: enhancement

#74 Add ui 5 to implement 2
  package.json
  src/App.js
  src/Routes.js
  src/assets/bg/circuit_dots.svg
  src/assets/content/search.svg
  src/components/molecules/Navbar/index.jsx
  src/components/molecules/Navbar/navbar.scss
  src/components/molecules/SearchBar/index.jsx
  src/components/molecules/TextTypist/index.jsx
  src/components/molecules/index.js
  src/components/organisms/sections/Login/index.jsx
  src/components/organisms/sections/Register/index.jsx
  src/components/organisms/sections/index.js
  src/components/pages/Landing/index.jsx
  src/components/pages/Landing/landing.scss
  src/index.js
Labels: enhancement, feature

#77 Improve intel 3 to implement 2
  src/intel/Database/Converter/index.js
Labels: bug, enhancement

#82 Add ui 6 to implement 2
  package.json
  src/App.js
  src/Routes.js
  src/components/molecules/Calendar2D/index.jsx
  src/components/molecules/Calendar3D/dummydata.js
  src/components/molecules/Calendar3D/index.jsx
  src/components/molecules/LanguageChart/index.jsx
  src/components/molecules/Socialdata/index.jsx
  src/components/organisms/sections/Register/index.jsx
  src/components/organisms/tabs/Overview/index.jsx
  src/components/pages/Landing/index.jsx
  src/components/pages/Profile/index.jsx
Labels: enhancement

#79 Add ui 7 to implement 2
  src/App.js
  src/components/molecules/Calendar3D/index.jsx
  src/components/molecules/ContribChart/index.jsx
  src/components/molecules/index.js
  src/components/organisms/sections/Register/index.jsx
  src/components/organisms/tabs/Overview/index.jsx
  src/components/pages/Profile/index.jsx
Labels: feature

#81 Add ui 8 to implement 2
  src/App.js
  src/Routes.js
  src/components/molecules/Calendar2D/index.jsx
  src/components/molecules/Calendar3D/index.jsx
  src/components/organisms/sections/Register/index.jsx
  src/components/pages/GitLab/index.jsx
  src/components/pages/Redirect/index.jsx
  src/components/pages/index.js
  src/intel/AuthGitLab/providers/gitlab.ts
  src/intel/AuthGitLab/services/utilities.js
  src/intel/OAuthGithub/providers/github.ts
Labels: enhancement

#85 Add Footer
  src/App.js
  src/Routes.js
  src/components/molecules/Footer/index.jsx
  src/components/molecules/index.js
Labels: feature

#91 Improve intel 4 to implement 2
  src/intel/Database/Converter/index.js
  src/intel/index.js
  src/intel/utils/UtilsGithub/Translator/index.js
Labels: enhancement

#94 Add ui 10 to implement 2
  src/components/molecules/Calendar3D/index.jsx
  src/components/organisms/sections/Login/index.jsx
  src/components/organisms/sections/Register/index.jsx
  src/components/pages/GitLab/index.jsx
Labels: enhancement

#97 Add ui 11 to implement 2
  src/components/organisms/tabs/Overview/index.jsx
Labels: enhancement
