Repository snek-at/front-legacy, pull requests merged in 2020-05, with the labels that each got.

#147 Add caching 1 to implement 4
  src/App.js
  src/components/organisms/sections/Register/index.jsx
Labels: enhancement

#148 Add gitlab streaks 1 to implement 4
  src/intel/utils/UtilsGitlab/index.js
Labels: bug, enhancement

#151 Add login on enter 1 to implement 4
  src/components/organisms/sections/Login/index.jsx
Labels: enhancement

#152 Add register on enter 1 to implement 4
  src/components/organisms/sections/Register/index.jsx
Labels: enhancement

#153 Add body background color 1 to implement 4
  src/utilities/_base.scss
Labels: enhancement

#154 Improve frontend ui 1 to implement 4
  .env.template
  package.json
  src/App.js
  src/components/molecules/Calendar2D/index.jsx
  src/components/molecules/Navbar/index.jsx
  src/components/molecules/Socialdata/index.jsx
  src/components/molecules/Socialdata/socialdata.scss
  src/components/molecules/TabContainer/index.jsx
  src/components/molecules/TabContainer/tabcontainer.scss
  src/components/organisms/tabs/Overview/index.jsx
  src/components/organisms/tabs/Projects/index.jsx
  src/components/organisms/tabs/Projects/projects.scss
  src/components/pages/Profile/index.jsx
  src/components/pages/Profile/profile.scss
  src/utilities/_base.scss
Labels: bug, enhancement, feature

#155 Adjust intel 1 to implement 4
  src/intel/Database/Converter/index.js
  src/intel/utils/UtilsGithub/Translator/index.js
  src/intel/utils/UtilsGitlab/index.js
Labels: enhancement

#156 Adjust database 1 to implement 4
  src/intel/Database/Statements/Select/index.js
Labels: enhancement

#158 Update pr template a1 to master
  PULL_REQUEST_TEMPLATE
Labels: documentation

#159 Improve caching 1 to Implement 4
  public/index.html
  src/App.js
  src/components/organisms/tabs/Projects/index.jsx
  src/intel/OAuthGithub/providers/github.ts
  src/intel/utils/UtilsWebscrap/index.js
Labels: enhancement

#160 Improve profile ab1 to implement 4
  src/components/molecules/Socialdata/index.jsx
Labels: enhancement

#161 Improve profile ab2 to Implement 4
  src/components/molecules/Calendar3D/index.jsx
Labels: enhancement
