Repository snek-at/front-legacy, pull requests merged in 2020-01, with the labels that each got.

#114 Add caching 1
  src/App.js
  src/components/organisms/sections/Register/index.jsx
Labels: enhancement

#126 Add bg 1 to implement-3
  package.json
  src/components/organisms/sections/Login/index.jsx
  src/components/organisms/sections/Register/index.jsx
  src/utilities/_base.scss
Labels: enhancement

#130 Improve frontend 1 to implement 3
  .env.template
  package.json
  src/App.js
  src/components/molecules/Calendar2D/index.jsx
  src/components/molecules/Navbar/index.jsx
  src/components/molecules/Socialdata/index.jsx
  src/components/molecules/Socialdata/socialdata.scss
  src/components/molecules/TabContainer/index.jsx
  src/components/molecules/TabContainer/tabcontainer.scss
  src/components/organisms/tabs/Overview/index.jsx
  src/components/organisms/tabs/Projects/index.jsx
  src/components/organisms/tabs/Projects/projects.scss
  src/components/pages/Profile/index.jsx
  src/components/pages/Profile/profile.scss
  src/utilities/_base.scss
Labels: bug, enhancement, feature

#134 Update intel 1 to implement 3
  src/intel/Database/Converter/index.js
  src/intel/utils/UtilsGithub/Translator/index.js
  src/intel/utils/UtilsGitlab/index.js
Labels: enhancement

#136 Update database 1 to implement 3
  src/intel/Database/Statements/Select/index.js
Labels: enhancement

#139 Improve profile 1 to implement 3
  src/components/molecules/Socialdata/index.jsx
Labels: enhancement

#115 Add gitlab streaks 1 to implement 3
  src/intel/utils/UtilsGitlab/index.js
Labels: bug, enhancement

#140 Improve caching 1 to Implement 3
  public/index.html
  src/App.js
  src/components/organisms/tabs/Projects/index.jsx
  src/intel/OAuthGithub/providers/github.ts
  src/intel/utils/UtilsWebscrap/index.js
Labels: enhancement
